spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:      ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true
      
  datasource:
    driver-class-name: org.postgresql.Driver    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: 123456
    
#postgresql
postgresql: 
  host: localhost
  port: 5432
  username: postgres
  password: 123456
  database: user_db